/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.theoremlp.pex4j;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

class SimpleJNITest {
    @Test void testFFI() {
        int[] output = SimpleJNIDemo.genRange();
        int[] expected = {0, 10, 20, 30, 40};
        Assertions.assertArrayEquals(output, expected);
    }
}
