/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.theoremlp.pex4j;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

class FFITest {
    @Test void testFFI() {
        String output = FFIDemo.sayHello("Rahul");
        Assertions.assertEquals(output, "Hello, Rahul!");
    }
}
