/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.theoremlp.demo;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

class SimpleJNITest {
    @Test void testFFI() {
        int[] output = SimpleJNIDemo.range(5);
        int[] expected = {0, 1, 2, 3, 4};
        Assertions.assertArrayEquals(output, expected);
    }
}
